from fpdf import FPDF
import os
from datetime import datetime


def generate_report(info, output_path=None):
    """
    Generate a PDF report for the threat analysis.
    
    Args:
        info: Dictionary containing threat information
        output_path: Path to save the report (default: report.pdf in project root)
    """
    if output_path is None:
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        output_path = os.path.join(base_dir, "report.pdf")
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Title
    pdf.set_font("Arial", style="B", size=16)
    pdf.cell(200, 15, txt="Cyber Threat Intelligence Report", ln=True)
    pdf.ln(5)
    
    # Timestamp
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt=f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(5)
    
    # Threat Information
    pdf.set_font("Arial", style="B", size=12)
    pdf.cell(200, 10, txt="Threat Analysis", ln=True)
    pdf.set_font("Arial", size=11)
    
    for k, v in info.items():
        pdf.cell(200, 8, txt=f"{k}: {v}", ln=True)
    
    # Footer
    pdf.ln(10)
    pdf.set_font("Arial", style="I", size=9)
    pdf.cell(200, 10, txt="This report was automatically generated by the Cyber Threat Intelligence System.", ln=True)
    
    pdf.output(output_path)
    return output_path
